version: 2.1
commands:
  setup-tools:
    description: "Setting up common tools"
    steps:
      - run:
          name: update apt caches
          command: 'apt update'
      - run:
          name: install sudo
          command: 'apt install -y sudo'
      - run:
          name: install git
          command: 'apt install -y git'
  setup-build:
    description: "Setting up the build environment by installing required dependencies."
    steps:
      - run:
          name: install gcc
          command: 'apt install -y gcc && apt install -y g++'
      - run:
          name: install make
          command: 'apt install -y make'
      - run:
          name: install cmake
          command: 'apt install -y cmake'
      - run:
          name: install python and pip for conan
          command: 'apt install -y python3 python3-pip'
      - run:
          name: install conan
          command: 'pip3 install conan'
jobs:
  build:
    docker:
      - image: "debian:buster"
    steps:
      - setup-tools
      - setup-build
      - checkout
      - run:
          - name: install dependencies with conan
            command: 'conan install .'
      - run:
          name: run cmake
          command: 'cmake .'
      - run:
          name: run make
          command: 'make -j $(nproc) doublebeam'
  test:
    docker:
      - image: "debian:buster"
    steps:
      - setup-tools
      - setup-build
      - checkout
      - run:
          name: install dependencies with conan
          command: 'conan install .'
      - run:
          name: run cmake
          command: 'cmake .'
      - run:
          name: run make
          command: 'make -j $(nproc) Unit_Tests_run'
      - run:
          name: run unit tests
          command: './tests/unit_tests/Unit_Tests_run --gtest_output=xml:test-results/googletest/results.xml'
      - store_test_results:
          path: test-results
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test