version: 2.1
commands:
  setup-tools:
    description: "Setting up common tools"
    steps:
      - run:
          name: update apt caches
          command: 'apt update'
      - run:
          name: install sudo
          command: 'apt install -y sudo'
      - run:
          name: install git
          command: 'apt install -y git'
  setup-build:
    description: "Setting up the build environment by installing required dependencies."
    steps:
      - run:
          name: install g++
          command: 'apt install -y g++'
      - run:
          name: install make and cmake
          command: 'apt install -y make cmake'
      - run:
          name: install python and pip for conan
          command: 'apt install -y python3 python3-pip'
      - run:
          name: install conan
          command: 'pip3 install conan'
      - run:
          name: detect settings for conan default profile
          command: 'conan profile new default --detect '
      - run:
          name: set libstdc++11 to use new ABI in gcc
          command: 'conan profile update settings.compiler.libcxx=libstdc++11 default'
jobs:
  build:
    docker:
      - image: "debian:buster"
    steps:
      - setup-tools
      - setup-build
      - checkout
      - run:
          name: install dependencies with conan
          command: 'conan install .'
      - run:
          name: run cmake
          command: 'cmake .'
      - run:
          name: build doublebeam
          command: 'cmake --build . --target doublebeam -- -j $(nproc)'
  test:
    docker:
      - image: "debian:buster"
    steps:
      - setup-tools
      - setup-build
      - checkout
      - run:
          name: install dependencies with conan
          command: 'conan install .'
      - run:
          name: run cmake
          command: 'cmake .'
      - run:
          name: build unit tests make
          command: 'cmake --build . --target Unit_Tests_run -- -j $(nproc)'
      - run:
          name: run unit tests
          command: './tests/unit_tests/Unit_Tests_run --gtest_output=xml:test-results/googletest/results.xml'
      - store_test_results:
          path: test-results
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test
