version: 2.1
commands:
  setup-tools:
    description: "Setting up common tools"
    steps:
      - run:
          name: update apt caches
          command: 'apt update'
      - run:
          name: install sudo
          command: 'apt install -y sudo'
      - run:
          name: install git
          command: 'apt install -y git'
  setup-build:
    description: "Setting up the build environment by installing required dependencies."
    steps:
      - run:
          name: install gcc
          command: 'apt install -y gcc && apt install -y g++'
      - run:
          name: install make
          command: 'apt install -y make'
      - run:
          name: install cmake
          command: 'apt install -y cmake'
      - run:
          name: install libboost-program-options
          command: 'apt install -y libboost-program-options-dev'
      - run:
          name: install libeigen3
          command: 'apt install -y libeigen3-dev'
      - run:
          name: install libfmt
          command: 'apt install -y libfmt-dev'
      - run:
          name: install libfftw3
          command: 'apt install -y libfftw3-dev'
      - run:
          name: install libmsgsl
          command: 'apt install -y libmsgsl-dev'
      - run:
          name: install zlib dependency
          command: 'apt install zlib1g-dev'
jobs:
  build:
    docker:
      - image: "debian:buster"
    steps:
      - setup
      - checkout
      - run:
          name: run cmake
          command: 'cmake .'
      - run:
          name: run make
          command: 'make doublebeam'
